core-app1:
  build: ./dotnet
  container_name: core-app1

core-app2:
  build: ./dotnet
  container_name: core-app2

core-app3:
  build: ./dotnet
  container_name: core-app3

nginx:
  build: ./nginx
  container_name: proxy
  ports:
    - 80:80
  links:
    - core-app1
    - core-app2
    - core-app3
